name: Lint Test and Deploy example
on: push
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci 
    lint:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: run lint
              run: echo "lint"
    tests:
        runs-on: ubuntu-latest
        needs: checkout
        steps:
            - name: run tests
              run: npm run test

